import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.awt.Color;


import org.junit.jupiter.api.Test;

/**
 * Unit tests for the Snake game classes.
 *
 * <p>Tests cover core functionality of the Snake and Grid classes,
 * including snake movement, growth, collision detection, and grid bounds.</p>
 */
public class SnakeGameTest {

     /**
     * Tests that the snake initializes at the correct starting position.
     */
    @Test 
    public void testSnakeInitialPosition() {
        Snake snake = new Snake(5,5);
        Segment head = snake.getHead();
        assertEquals(5, head.pos.row);
        assertEquals(5, head.pos.col);
    }

     /**
     * Tests that the snake moves correctly according to its velocity.
     */
    @Test 
    public void testSnakeMove() {
        Snake snake = new Snake(5,5);
        snake.setVelocity(1,0);
        snake.move();

        Segment head = snake.getHead();
        assertEquals(5, head.pos.row);
        assertEquals(6, head.pos.col);
    }

    /**
     * Tests that the snake grows by one segment after consuming food.
     */
    @Test 
    public void testSnakeGrow() {
        Snake snake = new Snake(5,5);
        snake.grow(Color.GREEN);
        snake.move();

        assertEquals(2, snake.getBody().size());
    }

     /**
     * Tests that the snake correctly detects collisions with itself.
     */
    @Test
    public void testCollision() {
        Snake snake = new Snake(5,5);

        snake.grow(Color.GREEN);
        snake.move();
        snake.grow(Color.BLUE);
        snake.move();
        snake.grow(Color.YELLOW);
        snake.move();


        snake.setVelocity(0, 1);
        snake.move();

        snake.setVelocity(-1, 0);
        snake.move();
        snake.grow(Color.ORANGE);

        snake.setVelocity(0, -1);
        snake.move();

        assertTrue(snake.checkCollision());
    }

     /**
     * Tests that the grid correctly identifies positions that are in or out of bounds.
     */
    @Test
    public void testGridInBounds() {
        Grid grid = new Grid(20,20 );
        assertTrue(grid.inBounds(new Position(10, 10)));
        assertFalse(grid.inBounds(new Position(-1, 10)));
        assertFalse(grid.inBounds(new Position(20,20)));


    }

    /**
     * Tests that random positions generated by the grid are within valid bounds.
     */
    @Test
    public void testGridRandomPosition() {
        Grid grid = new Grid(20, 20);
        Position p = grid.randomPosition();

        assertTrue(p.row >= 0 && p.row < 20);
        assertTrue(p.col >= 0 && p.col < 20);
    }
}
